name: Deploy MPG Signal

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yq \
            build-essential \
            python3-dev \
            libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip cache purge
          
          # Create corrected requirements file
          sed -e 's/pycoingecko==4.1.0/pycoingecko>=3.2.0/' \
              -e '/dexcreener-api/d' \
              requirements.txt > corrected_requirements.txt
              
          pip install --no-cache-dir -r corrected_requirements.txt
          pip check

      - name: Verify critical packages
        run: |
          python -c "
          import sys
          for pkg in ['numpy', 'pandas', 'pycoingecko']:
              try:
                  __import__(pkg)
                  print(f'✓ {pkg} imported successfully')
              except ImportError as e:
                  print(f'✗ {pkg} failed: {e}', file=sys.stderr)
                  sys.exit(1)
          "

      - name: Run application
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          echo "Starting application with Python $(python --version)"
          python src/main.py
