name: MPG Signal bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Recommended for better compatibility

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Install numpy first to avoid conflicts
          pip install numpy==1.26.0
          # Install requirements without dexcreener-api
          grep -v "dexcreener-api" requirements.txt > temp_requirements.txt
          pip install -r temp_requirements.txt
          rm temp_requirements.txt
          pip check

      - name: Verify installations
        run: |
          python -c "import numpy; print(f'NumPy {numpy.__version__} installed')"
          python -c "import pandas; print(f'Pandas {pandas.__version__} installed')"
          python -c "from pycoingecko import CoinGeckoAPI; print('PyCoinGecko available')"

      - name: Run bot
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python src/main.py
